include theos/makefiles/common.mk

BUNDLE_NAME = CustomBrightness
CustomBrightness_FILES = Switch.x
CustomBrightness_FRAMEWORKS = UIKit
CustomBrightness_LIBRARIES = flipswitch
CustomBrightness_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk