#!/bin/sh

killall customBrightnessd || true

chmod +x /usr/bin/customBrightnessd

chown 0:0 /System/LaunchDaemons/com.laughing-buddha-software.customBrightnessd.plist

launchctl load -w /System/LaunchDaemons/com.laughing-buddha-software.customBrightnessd.plist
